
spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3307/serverdb
    username : root

  jpa:
    hibernate:
      ddl-auto: create


    properties:
      hibernate:
        dilect: org.hibernate.dilect.MySQL8Dialect
        format_sql: true
    show-sql: true
